아이템 인터페이스 추가 및 공속증가 아이템(예시) 및 아이템 선택화면 연결 구현
HY-CtrlS/Universal-Invaders pull request #12
Opened 2024-11-12 16:01 UTC by Geguuuul

# 변경사항

## Core

1. 아이템 리스트 객체 추가

2. status 리셋할 때, 아이템 리스트 또한 level 0의 아이템들로 초기화

3. 아이템 선택화면 진입시에 items.getSelectedItemList()로 초기화한 아이템 리스트에서 최대 레벨인 아이템 삭제하고 무작위 3개 선택

## DrawManager

1. 아이템 선택화면 밑의 문구 수정 

2. 아이템 선택 시 해당 아이템의 설명이 출력되도록 변경.
selectedItem 값이 변하면서 itemList 값의 참조를 변경하며 게임을 크래시낼 가능성이 존재하므로 주의가 필요함. 
현재 해당 메소드만 보면 itemList가 원소가 2개 밖에 없을 때, 3번째로 이동하게 되면 selectedItem이 3이 되면서 ItemList(3)이 되면서 OutOfIndex가 나오는 경우가 있어서, 해당 부분을 따로 drawItems로 빼서 그렸고 또한, ItemSelectedScreen에서 selectedItem 변수와 관련하여 제한을 걸었음. 현재는 일어날 수 있는 부분을 막아두었음.

3. 아이템 스프라이트와 해당 아이템의 레벨을 표시하는 기능 추가(drawItem)
 -> 아이템을 선택하면 선택하고 나서 적용될 레벨을 표시해줘도 좋을듯.(추가적인 메소드가 필요할 것으로 생각)
기존의 drawEntity는 Entity들을 받아오는 거라서 안됨. 아이템은 개수가 많아질 것 같아서 아이템 폴더를 따로 만들었음

4. 아이템 스프라이트를 좀 크게 해서 그리는 drawBigItem 메소드 추가 

## Item

아이템 인터페이스 

현재 안쓰인 메소드들도 많은데, 후에 얼마나 구현하냐에 따라 사용 될수도 있는 것들을 일단은 추가 해둠. 프로젝트 마무리 단계때 필요없는 것들은 지우면서 리팩터링할 소요가 좀 있어보임.

이 메소드를 추가한 이유들은 주석으로 달아두었음.

## AttackSpeedUpItem

예시 공속증가 아이템 

현재 레벨에 따른 효과 변화 등은 구현되지 않은 상태임. 100 밀리초씩 빼도록 해 두었음. 

다른 아이템과 HP 시스템 등이 개선되어 본격적으로 추가되기 시작하면 조금씩 기능을 추가하고 넣어볼 예정

## ItemList

아이템들을 리스트로 관리해주는 클래스

Core에서 Status 초기화 하면서 레벨0의 아이템들의 객체가 하나씩 들어간 리스트로 초기화 시킴.(initializedItems())

getSelectedItemList를 통해 해당 아이템 리스트에서 먼저 최대 레벨에 도달한 아이템들을 제외하고 남은 아이템들 중에 무작위로 중복을 허용하지 않고 3개 선정함. 
이때 예외형으로 아이템이 3개 미만이 남은 경우 items를 그대로 return하여 넘겨줌.

# ItemSelectedScreen

메뉴 이동을 아이템을 2개 혹은 1개만 출시하게 될 경우 비어있는 칸으로 이동하지 못하도록 설정.

# 기타
최대한 간단하게 직관적이게 구현해본다고 한건데.... 복잡해진거 같습니다... 메트릭 분석했을 때, 몇몇 클래스의 RFC값이 좀 높게 나오긴 하는데, 아이템이라 화면으로 연결하는 것도 그렇고 Status에도 관여해서 어쩔 수 없이 높게 나오는 것 같습니다. 이보다 더 나은 구현사항 있으면 의견 주시면 반영하겠습니다. 

# 추가 얘기할 것 
이번 PR에 아이템 인터페이스 뿐만 아니라 아이템, 아이템 선택화면 연동에 대한 부분이 포함되어 버렸습니다. 근데 아이템 인터페이스만 추가하고 이러면 해당 기능에 대한 테스트 없이 main 에 합쳐지게 되는 부분이 있어서 이번에 그냥 최소한의 아이템을 추가하고 개발하는 방향으로 팀장님과 얘기하여 정했습니다. 이후에 작업 분할을 할 때, 이러한 테스트 가능성을 고려하면서 나누면 더 좋을 것 같습니다.

2024-11-12 16:49 UTC, Koominjae commented on src/Item/AttackSpeedUpItem.java
> +    // 현재 아이템이 최대 레벨인지에 대한 변수
`isMaxLevel()` 메소드에서 isMaxLevel 변수가 따로 필요없어서 지우신것 같은데 주석이 남았네요

2024-11-13 07:15 UTC, Koominjae requested changes

2024-11-13 07:15 UTC, Koominjae commented on src/Item/ItemList.java
> +      while (tempItemList.size() < 3 && !items.isEmpty()) {
```suggestion
      while (tempItemList.size() < 3) {
```
이미 if문의 조건으로 items의 사이즈가 3보다 크다는 것을 확인하고 while문이 실행되는 것이기 때문에 비어있는지 확인은 필요 없을 것 같습니다.

2024-11-13 07:15 UTC, Koominjae commented on src/Item/ItemList.java
> +    return new ArrayList<>(tempItemList);
현재 `return new ArrayList<>(tempItemList);` 부분이 if-else문 밖에 위치하고 있는데 while문 바로 뒤에 배치한다면 코드를 이해하기 좀 더 쉬울 것 같습니다.

2024-11-13 07:15 UTC, Koominjae commented on src/engine/Core.java
> +				// 게임 시작 시 StatusManage r의 status 객체를 res/status 의 값으로 초기화
StatusManager 오타

2024-11-13 07:15 UTC, Koominjae commented on src/Item/ItemList.java
ItemList 클래스에는 CtrlS 코드 스타일이 적용이 안되어 있습니다.

2024-11-13 07:15 UTC, Koominjae commented on src/engine/Core.java
> +				if (returnCode == 2) {
124번 줄에서 returnCode가 2로 변경되면 이 조건문이 실행되는 것 같은데, `case 1`에서 조건문으로 수행하는 것 보다 `case 2`에서 제일 위에 두어 바로 아이템 리스트를 생성하면 좋을 것 같습니다.

2024-11-13 07:15 UTC, Koominjae commented on src/engine/DrawManager.java
> +			String alarmString = "Only  " + itemList.size() + "  items remaining!!";
```suggestion
			String alarmString = "Only  " + itemList.size() + "  items left you can upgrade!!";
```
그냥 '남았다'고 표현하기 보다는 업그레이드 가능한 아이템의 수가 이만큼 남았다고 알려 주는 게 좋을 것 같습니다.

2024-11-13 07:15 UTC, Koominjae commented on src/engine/StatusManager.java
> +            status = new ShipStatus(750, -6, 2, 100);
```suggestion
            status = new ShipStatus(750, 6, 2, 100);
```
Default bulletSpeed가 음수로 되어 있어 수정이 필요합니다.

2024-11-13 07:26 UTC, Geguuuul commented on src/Item/ItemList.java
> +    return new ArrayList<>(tempItemList);
해당 메소드에 대한 return이 필요하므로 저  return 문은 필수적입니다. 그리고 위의 if else문은 아이템을 선정하는 과정이고, 거기서 선정된 아이템을 return하는 방식인데 좀 더 이해하기 쉽게 고쳐보겠씁니다

2024-11-13 07:38 UTC, Koominjae approved these changes

2024-11-13 07:38 UTC, merged

2024-11-17 15:45 UTC, suhynnoh commented
지금 방식은 Item이 추가될 때마다 새로운 Item 클래스가 추가되는 것으로 이해했는데, 각각의 아이템들은 클래스보단 인스턴스에 가깝지 않나 생각이듭니다. 추가로 ItemList도 클래스보다 실제 리스트로 구현하는 게 더 직관적일 것 같습니다.

제가 생각한 방식은 이렇습니다.
- Item, ItemManager 총 두 개의 클래스만 추가
- 아이템의 정보는 res폴더에서 JSON 파일로 관리 -> FileManager.loadItems() 메소드 추가
- 싱글톤 스타일의 ItemManager 클래스에서 Item 타입의 List로 아이템들 관리 (초기화시 FileManager.loadItems()에서 불러와 초기화)

2024-11-18 00:27 UTC, Geguuuul commented
구체적인 구현 예시를 들어주실 수 있을까요? json을 통해 데이터를 받는다고 하더라도 그 데이터를 ship에 적용을 할 메소드가 있어야 할텐데 현재 코드 상태에서는 단순히 ship 객체에만 적용한다고 될 아이템이 아닐수도 있습니다. 예를들어 스탯과 같은 아이템은 json에서 아이템이 스텟을 얼마나 올릴지 등에 대한 데이터를 load로 읽어오고 적용시키는 메소드를 활용할 수 있겠지만
부활과 같은 아이템이 추가되면 결국엔 적용시키는 메소드를 새로 추가하거나 ship에 목숨이라는 새로운 변수를 추가해야 합니다. 이것 뿐만 아니라 만약 체력흡수와 같은 효과는 ship에 해당 변수를 만들어 enemy와 연관시키든가 해당 아이템을 위한 메소드를 만들어하 합니다. 

결론적으로 아이템을 추가할때마다 ship객체에 변수가 추가 되거나 아이템마다의 적용 메소드가 있어야 될 것으로 보입니다. 제 생각은 이런데 다르게 생각하셨던 구현안이 있으신거면 말씀해주세요