CTRLS-35  체력 개편 (41, 42, 43)
HY-CtrlS/Universal-Invaders pull request #14
Opened 2024-11-13 11:13 UTC by Amarok121

## 개요

- 아군, 적 체력 및 총알의 공격력을 구현
- 각 EnemyShip 객체에 게임 레벨을 받아와서 레벨을 기준으로 체력을 설정.
- 적이 죽었을 때, 죽은 스프라이트가 나타나지 않고 바로 삭제되는 부분 수정.

## 변경사항

- hp 변수, 그리고 hp 변수를 get/set하기 위한 메서드 추가.
- damage 변수 및 getter/setter 추가.
- gamelevel에 따른 적의 체력 변경.
- CleanupCooldown을 통한 적 파괴 스프라이트 출력.

## 참고사항

- 관련 이슈 번호: #CTRLS-35, CTRLS-41, 42, 43

2024-11-13 16:30 UTC, Geguuuul reviewed
오류 발생 주석은 없에도 될 것 같습니다

2024-11-13 16:30 UTC, Geguuuul commented on src/engine/FileManager.java
> +            //오류 발생
```suggestion
           
```

2024-11-13 16:35 UTC, Amarok121 commented
> 오류 발생 주석은 없에도 될 것 같습니다

반영 완료하였습니다

2024-11-13 16:38 UTC, Geguuuul approved these changes
확인하였습니다

2024-11-13 16:54 UTC, Koominjae requested changes

2024-11-13 16:54 UTC, Koominjae commented on src/entity/Bullet.java
> +    private int damage = 1;
```suggestion
    private int damage;
```
아래 Bullet 생성자에서 damage를 입력받아 저장하기 때문에 초기값을 설정하지 않아도 될 것 같습니다. 추가로 변수에 대한 주석도 달아주세요. 없어도 상관은 없는데 코드 통일성을 위해 주석이 있으면 좋을 것 같습니다.

2024-11-13 16:54 UTC, Koominjae commented on src/entity/Bullet.java
>       */
주석에 새로 추가된 damage 파라미터에 대한 `@param` 내용이 추가되면 좋을 것 같습니다.

2024-11-13 16:54 UTC, Koominjae commented on src/entity/EnemyShip.java
> +    private int hp;
변수에 대한 주석 추가하면 좋을 것 같습니다.

2024-11-13 16:54 UTC, Koominjae commented on src/entity/EnemyShipFormation.java
> +                + shooter.width / 2, shooter.getPositionY(), BULLET_SPEED, 1, "Down", "ENEMY"));
```suggestion
                + shooter.width / 2, shooter.getPositionY(), BULLET_SPEED, 1, null, "ENEMY"));
```
안쓰이는 클래스이긴 하지만 굳이 수정하자면 모두 대문자로 "DOWN" 으로 하거나 null 값으로 해두면 될 것 같습니다.

2024-11-13 16:54 UTC, Koominjae commented on src/entity/Ship.java
> +    private int baseDamage;
변수에 대한 주석 추가하면 좋을 것 같습니다.

2024-11-13 16:54 UTC, Koominjae commented on src/entity/EnemyShipSet.java
> +    private int base_hp = 2;
```suggestion
    private int base_hp;
```
아래 setEnemyHp() 메소드를 통해 적군의 초기 hp를 설정하므로 따로 초기 값 할당은 필요 없을 것 같습니다. 
추가로 변수에 대한 주석 추가하면 좋을 것 같습니다.

2024-11-14 00:26 UTC, Geguuuul commented on src/entity/Ship.java
> +    private int baseDamage;
주석 수정하실때, maxLives는 지우셔도 상관없을 것 같습니다. 후에 목숨과 같은 기능 추가시에 다시 추가해도 될 거 같습니다.

2024-11-14 06:05 UTC, Koominjae approved these changes

2024-11-14 06:11 UTC, merged