[CTRLS-35]-44, 45: 데미지 입는 방식 변경, 체력 자동 재생
HY-CtrlS/Universal-Invaders pull request #19
Opened 2024-11-16 16:02 UTC by Amarok121

## 개요

- 적과 접촉 시 데미지를 0.2초마다 받도록 수정
- 현재 체력이 최대 체력(100)보다 적을 경우, 5초마다 체력을 1씩 재생함.

## 변경사항

- Ship: destructionCooldown을 200milliseconds로 변경, 데미지 빈도 증가
- GameScreen: 체력 재생을 위한 hpRegenCooldown 변수, 최대 체력을 계산하기 위한 maxHp 변수 생성. (기본값 100)
hpRegen() 메서드가 주기적으로(5초) 호출, 최대 체력보다 적으면 체력 1회복

## 참고사항

- 관련 이슈 번호: #CTRLS-35

2024-11-16 19:31 UTC, Geguuuul commented
적과 접촉시 연속데미지를 받게 하도록 기능 구현이 안되었습니다. 저희가 토의했던 건 적과 접촉해 있는 동안 체력이 연속적으로 다는 형태였습니다. 단순히 받는 데미지를 줄이고 무적시간을 줄이는 구조가 아닙니다

2024-11-17 02:57 UTC, Amarok121 commented
> 적과 접촉시 연속데미지를 받게 하도록 기능 구현이 안되었습니다. 저희가 토의했던 건 적과 접촉해 있는 동안 체력이 연속적으로 다는 형태였습니다. 단순히 받는 데미지를 줄이고 무적시간을 줄이는 구조가 아닙니다

// 적과 아군 함선의 충돌 체크
        for (EnemyShip enemyShip : enemis) {
            if (checkCollision(this.ship, enemyShip)) {
                if (!this.ship.isDestroyed() && !enemyShip.isDestroyed() && !levelFinished) {
                    //this.enemyShipSet.damage_Enemy(enemyShip, this.ship.getBaseDamage());
                    this.ship.destroy();
                    this.hp -= 5;
                    this.logger.info("Hit on player ship, -5 HP");
                    Core.getSoundManager().playDamageSound();
                    if (this.hp <= 0 && !this.isDestroyed) {
                        Core.getSoundManager().playExplosionSound();
                        this.isDestroyed = true;
                    }
                }
            }
        }
        
       1레벨에서 해당 기능이 작동하지 않는 것처럼 보이는 이유는 충돌 시 적 함선에게 데미지가 들어가며 파괴되기 때문입니다. 해당 부분을 주석 처리하여 상시 작동하도록 조정하겠습니다.

2024-11-17 07:15 UTC, Geguuuul requested changes
이 부분이 현재 그냥 100을 대입해서 최대 HP로 설정해 두었는데, 인게임에서 HP에 대한 부분은 status라는 싱글톤 객체에서 사용하고 있으므로 여기서 받아와서 최대 HP를 설정해주는 것이 좀 더 유기적으로 연결된 코드를 만들 거 같습니다. 지금은 아이템에서 status에 HP가 변화가 생기더라도 최대 HP에는 변화가 생기지 않아서 변경이 필요해 보입니다.

2024-11-17 07:15 UTC, Geguuuul commented on src/screen/GameScreen.java
> +    private int maxHp = 100;
`private int maxHp = 100;`

2024-11-17 08:20 UTC, Amarok121 commented on src/screen/GameScreen.java
> +    private int maxHp = 100;
```suggestion
    private int maxHp = Core.getStatusManager().getHp();
```

2024-11-17 08:29 UTC, Geguuuul requested changes
현재 게임에서 적에게 맞으면서 죽을 때, 체력 1에서 맞으면 -4가 되는 등의 마이너스 체력이 있습니다. 그래서 체력을 깎기 전에 깎을 때 체력이 0 이하가 되는지를 체크해서 0보다 크면 5를 깎고 0 이하가 되면 깎지 말고 0으로 바꿔버리도록 하는게 나을 거 같습니다.

2024-11-17 08:29 UTC, Geguuuul commented on src/screen/GameScreen.java
> +                    this.hp -= 5;
```suggestion
                    this.hp = (this.hp - 5 > 0) ? this.hp - 5 : 0;
```

2024-11-17 08:36 UTC, Geguuuul commented
위 사항만 확인되면 괜찮은 것 같습니다. 이후에 스프라이트나 사운드 부분에 대해서는 팀원들과의 협의과 필요할 것 같습니다. 개인적으로 사운드 부분이 재생되면서 시끄러운 감이 약간 있는 거 같습니다

2024-11-17 09:13 UTC, Geguuuul approved these changes

2024-11-17 09:13 UTC, merged

2024-11-17 13:01 UTC, suhynnoh commented on src/screen/GameScreen.java
> +    private int maxHp = 100;
하드코딩을 최소화 하는 방식 좋은 것 같습니다!